### ISSUE TITLE
Module error in backend

### ISSUE THREAD

**Issue by ilkr** [chrisrollins65/cr_translate_mate#1]
Unknown: Argument 1 passed to ModelModuleCrTranslateMate::pathToArray() must be of the type array, string given, called in /public_html/admin/model/module/cr_translate_mate.php on line 257 and defined in /public_html/admin/model/module/cr_translate_mate.php on line 244Warning: Illegal string offset 'common' in /public_html/admin/model/module/cr_translate_mate.php on line 249Unknown: Argument 1 passed to ModelModuleCrTranslateMate::pathToArray() must be of the type array, string given, called in /public_html/admin/model/module/cr_translate_mate.php on line 257 and defined in /public_html/admin/model/module/cr_translate_mate.php on line 244Warning: Illegal string offset 'gen_example' in /public_html/admin/model/module/cr_translate_mate.php on line 249Unknown: Argument 1 passed to ModelModuleCrTranslateMate::pathToArray() must be of the type array, string given, called in /public_html/admin/model/module/cr_translate_mate.php on line 257 and defined in /public_html/admin/model/module/cr_translate_mate.php on line 244Warning: Illegal string offset 'gen_index' in /public_html/admin/model/module/cr_translate_mate.php on line 249Unknown: Argument 1 passed to ModelModuleCrTranslateMate::pathToArray() must be of the type array, string given, called in /public_html/admin/model/module/cr_translate_mate.php on line 257 and defined in /public_html/admin/model/module/cr_translate_mate.php on line 244Warning: Illegal string offset 'gen_setting' in /public_html/admin/model/module/cr_translate_mate.php on line 249

**Comment by chrisrollins65** [comment]
Hi ilkr, could you let me know what version of Opencart you're using?
Also, do you know what version of PHP you have?

**Comment by ilkr** [comment]
Hi,
Opencart version 2.0.3.1
PHP Version 5.5.9-1 on ubuntu 4.11

**Comment by chrisrollins65** [comment]
I'm unable to reproduce your error, but I've made a small update to the file upload/admin/model/module/cr_translate_mate.php

Try downloading it into your application and see if it helps. If not, it'd help if you could show me the layout of the files in your language folder.

**Comment by ilkr** [comment]
Hi Chris,
This update solve problem.
Thanks.
