### ISSUE TITLE
errors in Version OC 2.3

### ISSUE THREAD

**Issue by hbmax** [chrisrollins65/cr_translate_mate#11]
we installed translatemate to OC 2.3 according to your additional instructions as below:
Installation is a little more complicated though. When you first enable the extension, you have to go to the user settings and give your user permissions to view and edit the module. Then you need to deactivate and reactivate the extension. You may need to log out and back in to Open Cart as well.
but we are getting certain messages we dont know if its installed correctly...
![translatemate messages after installation on oc 2 3](https://user-images.githubusercontent.com/31760405/30425555-427eb1d6-9952-11e7-9897-10355bfdbf5d.png)

**Comment by chrisrollins65** [comment]
@hbmax I have an idea about what was causing this issue and it should be resolved in the newest version I've just uploaded. The newest version is only for OpenCart 3, so give it a shot if that's what you're using. If you're still using OpenCart 2 and wish to use this extension still, let me know and I'll see about back-porting the solution for the previous version of this extension.
