### ISSUE TITLE
2 errors in Version 2.2.0.0

### ISSUE THREAD

**Issue by bgdz** [chrisrollins65/cr_translate_mate#5]
If I click on Front End or Back End I get this,
"Error

Fatal error: Call to undefined function error_handler() in .../admin/controller/module/cr_translate_mate.php on line 131

Fatal error: Call to a member function write() on a non-object in .../admin/controller/module/cr_translate_mate.php on line 155"

**Comment by chrisrollins65** [comment]
Thanks for the info, bgdz. I'll look into it again, but from what I saw last time I looked into this error, they did some pretty strange things in version 2.2.0.0 that don't seem correct to me.

For the moment I recommend using a previous version of OpenCart if you need this extension.

**Comment by chrisrollins65** [comment]
OK, I found some time this week to look into this and have updated the extension so that it should now work with OpenCart 2.2.0.0. The errors you mentions should be resolved, so I'll go ahead and close this. Let me know if you run into any other issues.

**Comment by hbmax** [comment]
we installed translatemate to OC 2.3 according to your additional instructions as below:
Installation is a little more complicated though. When you first enable the extension, you have to go to the user settings and give your user permissions to view and edit the module. Then you need to deactivate and reactivate the extension. You may need to log out and back in to Open Cart as well.
but we are getting certain messages we dont know if its installed correctly...
![translatemate messages after installation on oc 2 3](https://user-images.githubusercontent.com/31760405/30201311-f7a8af78-9482-11e7-9418-7ebd1858b1a1.png)

**Comment by hbmax** [comment]
we installed translatemate to OC 2.3 according to your additional instructions as below:
Installation is a little more complicated though. When you first enable the extension, you have to go to the user settings and give your user permissions to view and edit the module. Then you need to deactivate and reactivate the extension. You may need to log out and back in to Open Cart as well.
but we are getting certain messages we dont know if its installed correctly...

**Comment by hbmax** [comment]
we solved 
it was because of php version problem
